more dockerfile changes

diff --git a/zap/dockerfile b/zap/dockerfile
--- a/zap/dockerfile
+++ b/zap/dockerfile
@@ -1,26 +1,43 @@
 FROM ghcr.io/zaproxy/zaproxy:stable
 
-# Create a startup script that forces HTTP mode
-RUN echo '#!/bin/bash' > /usr/local/bin/start-http.sh && \
-    echo 'echo "Starting ZAP in HTTP-only mode on port $PORT..."' >> /usr/local/bin/start-http.sh && \
-    echo 'exec zap.sh -daemon \' >> /usr/local/bin/start-http.sh && \
-    echo '    -host 0.0.0.0 \' >> /usr/local/bin/start-http.sh && \
-    echo '    -port $PORT \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.key=aaef54aee7ea6b3df86e50f888a8d2c7 \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config hud.enabled=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.addrs.addr.name=.* \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.addrs.addr.regex=true \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config connection.followRedirect=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config connection.postFormRedirects=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config oast.service.callback.enabled=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config network.proxy.chain.enabled=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config network.connection.proxyChain.skipName=.* \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.disablekey=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.secure=false \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config api.nohttps=true \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config network.connection.httpOnly=true \' >> /usr/local/bin/start-http.sh && \
-    echo '    -config connection.timeoutInSecs=60' >> /usr/local/bin/start-http.sh
+USER root
+RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*
 
-RUN chmod +x /usr/local/bin/start-http.sh
+# Remove default nginx configs
+RUN rm -f /etc/nginx/sites-enabled/default /etc/nginx/conf.d/default.conf
 
-CMD ["/usr/local/bin/start-http.sh"]
+# Create nginx config that properly handles Render's HTTPS termination
+RUN echo 'server {' > /etc/nginx/conf.d/app.conf && \
+    echo '    listen $PORT;' >> /etc/nginx/conf.d/app.conf && \
+    echo '    server_name _;' >> /etc/nginx/conf.d/app.conf && \
+    echo '' >> /etc/nginx/conf.d/app.conf && \
+    echo '    # Tell nginx this is already HTTPS (from Render termination)' >> /etc/nginx/conf.d/app.conf && \
+    echo '    set $forwarded_proto $http_x_forwarded_proto;' >> /etc/nginx/conf.d/app.conf && \
+    echo '    if ($forwarded_proto = "") {' >> /etc/nginx/conf.d/app.conf && \
+    echo '        set $forwarded_proto "https";' >> /etc/nginx/conf.d/app.conf && \
+    echo '    }' >> /etc/nginx/conf.d/app.conf && \
+    echo '' >> /etc/nginx/conf.d/app.conf && \
+    echo '    location / {' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_pass http://127.0.0.1:8081;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_set_header Host $host;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_set_header X-Real-IP $remote_addr;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_set_header X-Forwarded-Proto $forwarded_proto;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_redirect off;' >> /etc/nginx/conf.d/app.conf && \
+    echo '        proxy_intercept_errors off;' >> /etc/nginx/conf.d/app.conf && \
+    echo '    }' >> /etc/nginx/conf.d/app.conf && \
+    echo '}' >> /etc/nginx/conf.d/app.conf
+
+# Create startup script
+RUN echo '#!/bin/bash' > /usr/local/bin/start.sh && \
+    echo 'set -e' >> /usr/local/bin/start.sh && \
+    echo 'echo "Starting ZAP..."' >> /usr/local/bin/start.sh && \
+    echo 'su zap -c "zap.sh -daemon -host 127.0.0.1 -port 8081 -config api.key=aaef54aee7ea6b3df86e50f888a8d2c7 -config hud.enabled=false -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config connection.followRedirect=false -config connection.postFormRedirects=false -config oast.service.callback.enabled=false -config network.proxy.chain.enabled=false -config network.connection.proxyChain.skipName=.* -config api.disablekey=false -config api.secure=false -config api.nohttps=true" &' >> /usr/local/bin/start.sh && \
+    echo 'sleep 10' >> /usr/local/bin/start.sh && \
+    echo 'echo "Starting nginx with PORT substitution..."' >> /usr/local/bin/start.sh && \
+    echo 'envsubst '"'"'$PORT'"'"' < /etc/nginx/conf.d/app.conf > /tmp/app.conf && mv /tmp/app.conf /etc/nginx/conf.d/app.conf' >> /usr/local/bin/start.sh && \
+    echo 'nginx -g "daemon off;"' >> /usr/local/bin/start.sh
+
+RUN chmod +x /usr/local/bin/start.sh
+
+CMD ["/usr/local/bin/start.sh"]
